/*
This file contains all would-be-magic-strings in the app.
*/

module.exports = {
	// MISC
	FIREBASE: "https://reduxfirebase.firebaseio.com/",

	// UI FEEDBACK ACTIONS
	DISPLAY_ERROR: "DISPLAY_ERROR",
	DISPLAY_MESSAGE: "DISPLAY_MESSAGE",
	DISMISS_FEEDBACK: "DISMISS_FEEDBACK",

	// AUTH ACTIONS
	ATTEMPTING_LOGIN: "ATTEMPTING_LOGIN",
	LOGIN_USER: "LOGIN_USER",
	LOGOUT: "LOGOUT",

	// AUTH STATES
	LOGGED_IN: "LOGGED_IN",
	ANONYMOUS: "ANONYMOUS",
	AWAITING_AUTH_RESPONSE: "AWAITING_AUTH_RESPONSE",

	// QUOTE ACTIONS
	RECEIVE_QUOTES_DATA: "RECEIVE_QUOTES_DATA",
	AWAIT_NEW_QUOTE_RESPONSE: "AWAIT_NEW_QUOTE_RESPONSE",
	RECEIVE_NEW_QUOTE_RESPONSE: "RECEIVE_NEW_QUOTE_RESPONSE",
	START_QUOTE_EDIT: "START_QUOTE_EDIT",
	FINISH_QUOTE_EDIT: "FINISH_QUOTE_EDIT",
	SUBMIT_QUOTE_EDIT: "SUBMIT_QUOTE_EDIT",

	// QUOTE STATES
	EDITING_QUOTE: "EDITING_QUOTE",
	SUBMITTING_QUOTE: "SUBMITTING_QUOTE"
};